SKIN CARE/Models/Kategorite.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SKIN_CARE.Models
{
    [Table("Kategorite")]
    public class Kategorite
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Emri i kategorise eshte i kerkuar!")]
        [Display(Name = "Emri Kategorise")]
        public string EmriKategorise { get; set; }
        public virtual ICollection<Produktet> Produktet { get; set; }
    }
}

SKIN CARE/Controllers/KategoritesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SKIN_CARE.Models;

namespace SKIN_CARE.Controllers
{
    public class KategoritesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Kategorites
        public ActionResult Index()
        {
       
            return View(db.Kategorite.ToList());
        }

        [HttpGet]
        public ActionResult KerkoKategori(string kategori)
        {

            if (!string.IsNullOrEmpty(kategori))
            {
                return Json( db.Kategorite.Where(s => s.EmriKategorise.Contains(kategori)), JsonRequestBehavior.AllowGet);
            }
            return View(db.Kategorite.ToList());
        }

       

        // GET: Kategorites/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kategorite kategorite = db.Kategorite.Find(id);
            if (kategorite == null)
            {
                return HttpNotFound();
            }
            return View(kategorite);
        }

        [Authorize(Roles = "Admin")]
        // GET: Kategorites/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Kategorites/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,EmriKategorise")] Kategorite kategorite)
        {
            if (ModelState.IsValid)
            {
                db.Kategorite.Add(kategorite);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(kategorite);
        }

        [Authorize(Roles = "Admin")]
        // GET: Kategorites/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kategorite kategorite = db.Kategorite.Find(id);
            if (kategorite == null)
            {
                return HttpNotFound();
            }
            return View(kategorite);
        }

        // POST: Kategorites/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,EmriKategorise")] Kategorite kategorite)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kategorite).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kategorite);
        }

        [Authorize(Roles = "Admin")]
        // GET: Kategorites/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kategorite kategorite = db.Kategorite.Find(id);
            if (kategorite == null)
            {
                return HttpNotFound();
            }
            return View(kategorite);
        }

        // POST: Kategorites/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Kategorite kategorite = db.Kategorite.Find(id);
            db.Kategorite.Remove(kategorite);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SKIN CARE/Controllers/ProduktetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using SKIN_CARE.Models;

namespace SKIN_CARE.Controllers
{
    
    public class ProduktetsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        
        // GET: Produktets
        public ActionResult Index(int? id, string search, int? kategoriID, string rendit)
        {

            if (id != null)
            {
                var produkt = from p in db.Produktet
                              where p.MarkaID == id
                              select p;
                return View(produkt);
            }
            else
                if (!string.IsNullOrEmpty(search))
            {
                var prod = from p in db.Produktet
                           where p.Emri.Contains(search)
                           select p;
                return View(prod);
            }
            else
                if (kategoriID != null)
            {
                var produkt = from p in db.Produktet
                              where p.KategoriID == kategoriID
                              select p;
                return View(produkt);
            }

            else
                ViewData["Renditja"] = string.IsNullOrEmpty(rendit) ? "desc" : "";
                ViewData["Renditja"] = string.IsNullOrEmpty(rendit) ? "asc" : "";
            switch (rendit)
            {
                case "desc":
                    return View(db.Produktet.OrderByDescending(p => p.Cmimi).ToList());
                case "asc":
                    return View(db.Produktet.OrderBy(p => p.Cmimi).ToList());
                case "all":
                    return View(db.Produktet.ToList());
            }
            return View(db.Produktet.ToList());
        }


        public ActionResult ShtoNeKart(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produktet produkte = db.Produktet.Find(id);
            if (produkte == null)
            {
                return HttpNotFound();
            }
            if (Request.IsAuthenticated)
            {
                string userId = User.Identity.GetUserId();
                ApplicationUser perdoruesi = db.Users.FirstOrDefault(x => x.Id == userId);
                ViewBag.Username = "Pershendetje " + perdoruesi.UserName;

                if (userId != null)
                {

                    if (Session["kart"] == null)
                    {
                        List<Karta> kart = new List<Karta>();

                        kart.Add(new Karta
                        {
                            Produktet = produkte,
                            Sasia = 1
                        });
                        Session["kart"] = kart;
                    }
                    else
                    {
                        List<Karta> kart = (List<Karta>)Session["kart"];
                        int index = isExist(id);
                        if (index != -1)
                        {
                            kart[index].Sasia++;
                        }
                        else
                        {
                            kart.Add(new Karta()
                            {
                                Produktet = produkte,
                                Sasia = 1
                            });
                        }
                        Session["kart"] = kart;
                    }

                }
            }
            //Karta Guest
            else
            {
                ViewBag.Username = "Guest";
                if (Session["guest"] == null)
                {
                    List<Karta> kart = new List<Karta>();

                    kart.Add(new Karta
                    {
                        Produktet = produkte,
                        Sasia = 1
                    });
                    Session["guest"] = kart;
                }
                else
                {
                    List<Karta> kart = (List<Karta>)Session["guest"];
                    int index = Ekziston(id);
                    if (index != -1)
                    {
                        kart[index].Sasia++;
                    }
                    else
                    {
                        kart.Add(new Karta()
                        {
                            Produktet = produkte,
                            Sasia = 1
                        });
                    }
                    Session["guest"] = kart;
                }



            }
            return View("ShtoNeKart");

        }

        public ActionResult Remove(int id)
        {
            List<Karta> kart = (List<Karta>)Session["kart"];
            int index = isExist(id);
            kart.RemoveAt(index);
            Session["kart"] = kart;
            return View("ShtoNeKart");
        }

        private int isExist(int? id)
        {
            List<Karta> kart = (List<Karta>)Session["kart"];
            for (int i = 0; i < kart.Count; i++)
                if (kart[i].Produktet.ID.Equals(id))
                    return i;
            return -1;
        }

        private int Ekziston(int? id)
        {
            List<Karta> kart = (List<Karta>)Session["guest"];
            for (int i = 0; i < kart.Count; i++)
                if (kart[i].Produktet.ID.Equals(id))
                    return i;
            return -1;
        }
        public ActionResult Fshi(int id)
        {
            List<Karta> kart = (List<Karta>)Session["guest"];
            int index = Ekziston(id);
            kart.RemoveAt(index);
            Session["guest"] = kart;
            return View("ShtoNeKart");
        }


        [Authorize]
        // GET: Produktets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produktet produktet = db.Produktet.Find(id);
            if (produktet == null)
            {
                return HttpNotFound();
            }
            return View(produktet);
        }

        [Authorize(Roles = "Admin")]
        // GET: Produktets/Create
        public ActionResult Create()
        {
            ViewBag.KategoriID = new SelectList(db.Kategorite, "ID", "EmriKategorise");
            ViewBag.MarkaID = new SelectList(db.Markat, "ID", "EmriMarkes");
            return View();
        }

        // POST: Produktets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Emri,Imazhi,Pershkrimi,Cmimi,KategoriID,MarkaID")] Produktet produktet, HttpPostedFileBase Imazhi)
        {
            ViewBag.KategoriID = new SelectList(db.Kategorite, "ID", "EmriKategorise", produktet.KategoriID);
            ViewBag.MarkaID = new SelectList(db.Markat, "ID", "EmriMarkes", produktet.MarkaID);

            if (ModelState.IsValid)
            {
                WebImage img = new WebImage(Imazhi.InputStream);
                img.Save(Konstante.ImazhPath + Imazhi.FileName);

                db.Produktet.Add(new Produktet
                {
                    Emri = produktet.Emri,
                    Imazhi = Imazhi.FileName,
                    Pershkrimi = produktet.Pershkrimi,
                    Cmimi = produktet.Cmimi,
                    KategoriID = produktet.KategoriID,
                    MarkaID = produktet.MarkaID

                });
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(produktet);
        }

        [Authorize(Roles = "Admin")]
        // GET: Produktets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produktet produktet = db.Produktet.Find(id);
            if (produktet == null)
            {
                return HttpNotFound();
            }
            ViewBag.KategoriID = new SelectList(db.Kategorite, "ID", "EmriKategorise", produktet.KategoriID);
            ViewBag.MarkaID = new SelectList(db.Markat, "ID", "EmriMarkes", produktet.MarkaID);
            return View(produktet);
        }

        // POST: Produktets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Emri,Imazhi,Pershkrimi,Cmimi,KategoriID,MarkaID")] Produktet produktet)
        {
            ViewBag.KategoriID = new SelectList(db.Kategorite, "ID", "EmriKategorise", produktet.KategoriID);
            ViewBag.MarkaID = new SelectList(db.Markat, "ID", "EmriMarkes", produktet.MarkaID);
            if (ModelState.IsValid)
            {
                db.Entry(produktet).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(produktet);
        }
        [Authorize(Roles = "Admin")]
        // GET: Produktets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produktet produktet = db.Produktet.Find(id);
            if (produktet == null)
            {

SKIN CARE/Views/Kategorites/Create.cshtml
@model SKIN_CARE.Models.Kategorite

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Kategorite</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmriKategorise, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmriKategorise, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmriKategorise, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SKIN CARE/Views/Kategorites/Delete.cshtml
@model SKIN_CARE.Models.Kategorite

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Kategorite</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EmriKategorise)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmriKategorise)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SKIN CARE/Views/Kategorites/Details.cshtml
@model SKIN_CARE.Models.Kategorite

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Kategorite</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EmriKategorise)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmriKategorise)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SKIN CARE/Views/Kategorites/Edit.cshtml
@model SKIN_CARE.Models.Kategorite

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Kategorite</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.EmriKategorise, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmriKategorise, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmriKategorise, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SKIN CARE/Views/Kategorites/Index.cshtml
@model IEnumerable<SKIN_CARE.Models.Kategorite>

@{
    ViewBag.Title = "Index";
}
<h3>Filtro sipas kategorise</h3>
@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}

<input type="text" id="value" placeholder="Emri Kategorise" />
 <button id="btn" onclick="kerko()">Kliko</button>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EmriKategorise)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.EmriKategorise, "Index", "Produktets", new { kategoriID = item.ID }, null)
            </td>
            <td>
                @if (User.IsInRole("Admin"))
                {
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) <br />
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                }
            </td>
        </tr>
    }

</table>
@section Scripts {
    <script>
        function kerko() {
            var kategori = $("#value").val();
            if (kategori == "") {
                alert("Shkruani emrin e kategorise")
            }
            else {
                $.ajax({
                    type: 'GET',
                    url: "/Kategorites/KerkoKategori",
                    data: {
                        kategori: kategori,
                    },
                    success: function (data) {
                        if (data == "") {
                            alert("Nuk ndodhet asnje  kategori me kete emer");
                        }
                        else {
                            $('.table').html(data);
                        }
                    }
                });
            }
        }
    </script>
   }